[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
    default-src 'self' https://discord.com;
    script-src 'self' 'unsafe-inline' 'unsafe-eval' https://discord.com https://1336536163313520670.discordsays.com;
    connect-src 'self' https://discord.com https://1336536163313520670.discordsays.com data:;
    frame-ancestors 'self' https://discord.com;
    img-src 'self' data:;
    manifest-src 'self';
    """
